# Generated by Django 4.2.7 on 2024-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография')),
                ('task', models.TextField(verbose_name='Описание')),
                ('short_task', models.TextField(max_length=255, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('short_task', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('cena', models.CharField(max_length=255, verbose_name='Cтоимость')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('short_task', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('cena', models.CharField(max_length=255, verbose_name='Cтоимость')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Экскурсии',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('short_task', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('cena', models.CharField(max_length=255, verbose_name='Cтоимость')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Выпускные',
                'verbose_name_plural': 'Выпускные',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('short_task', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('cena', models.CharField(max_length=255, verbose_name='Cтоимость')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Мастер-классы',
                'verbose_name_plural': 'Мастер-классы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография')),
                ('task', models.TextField(blank=True, verbose_name='Описание')),
                ('short_task', models.TextField(max_length=255, verbose_name='Краткое описание')),
                ('cena', models.CharField(max_length=255, verbose_name='Cтоимость')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-time_create'],
            },
        ),
    ]
